# Generated by Django 5.2.4 on 2025-08-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_rating_remove_product_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
