# Generated by Django 5.2.4 on 2025-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
