# Generated by Django 5.2.4 on 2025-08-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
