# Generated by Django 5.2.4 on 2025-08-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wishlist', '0002_vehicle_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
