# Generated by Django 5.2.5 on 2025-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='token',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
